export default {
  LOCAL_PLAYER_CONNECT       : 'LOCAL_PLAYER_CONNECT',
  SET_QUESTION_BANK          : 'SET_QUESTION_BANK',
  SET_SESSION_PROPS          : 'SET_SESSION_PROPS',
  SET_LOCAL_PLAYER_PROPS     : 'SET_LOCAL_PLAYER_PROPS',
  SET_LOCAL_PLAYER_NAME      : 'SET_LOCAL_PLAYER_NAME',
  SET_LOCAL_PLAYER_APPEARANCE: 'SET_LOCAL_PLAYER_APPEARANCE',
  SET_REMOTE_PLAYER_PROPS    : 'SET_REMOTE_PLAYER_PROPS',
  RESET_GAME                 : 'RESET_GAME',
  SET_SENT_QUESTION          : 'SET_SENT_QUESTION',
  SET_CURRENT_QUESTION       : 'SET_CURRENT_QUESTION',
  CLEAR_QUESTION             : 'CLEAR_QUESTION',
  ANSWERED_CORRECT           : 'ANSWERED_CORRECT',
  ANSWERED_INCORRECT         : 'ANSWERED_INCORRECT',
  OPPONENT_ANSWERED          : 'OPPONENT_ANSWERED',
  APPLY_RISK                 : 'APPLY_RISK'
};