module.exports = {
  CHANGE_GAME_STATE          : 'CHANGE_GAME_STATE',
  LOCAL_PLAYER_CONNECT       : 'LOCAL_PLAYER_CONNECT',
  SELECT_PLAYER              : 'SELECT_PLAYER',
  REMOTE_PLAYER_CONNECT      : 'REMOTE_PLAYER_CONNECT',
  GAME_START                 : 'GAME_START',
  LOCAL_QUESTION             : 'LOCAL_QUESTION',
  REMOTE_QUESTION            : 'REMOTE_QUESTION',
  LOCAL_PLAYER_HEALTH_CHANGE : 'LOCAL_PLAYER_HEALTH_CHANGE',
  REMOTE_PLAYER_HEALTH_CHANGE: 'REMOTE_PLAYER_HEALTH_CHANGE',
  GAME_OVER                  : 'GAME_OVER'
};