module.exports = {
  LOCAL_PLAYER_CONNECT       : 'LOCAL_PLAYER_CONNECT',
  SET_SESSION_PROPS          : 'SET_SESSION_PROPS',
  SET_LOCAL_PLAYER_PROPS     : 'SET_LOCAL_PLAYER_PROPS',
  SET_LOCAL_PLAYER_NAME      : 'SET_LOCAL_PLAYER_NAME',
  SET_LOCAL_PLAYER_APPEARANCE: 'SET_LOCAL_PLAYER_APPEARANCE',
  SET_REMOTE_PLAYER_PROPS    : 'SET_REMOTE_PLAYER_PROPS',
  RESET_GAME                 : 'RESET_GAME'
  //SELECT_PLAYER              : 'SELECT_PLAYER',
  //REMOTE_PLAYER_CONNECT      : 'REMOTE_PLAYER_CONNECT',
  //GAME_START                 : 'GAME_START',
  //LOCAL_QUESTION             : 'LOCAL_QUESTION',
  //REMOTE_QUESTION            : 'REMOTE_QUESTION',
  //LOCAL_PLAYER_HEALTH_CHANGE : 'LOCAL_PLAYER_HEALTH_CHANGE',
  //REMOTE_PLAYER_HEALTH_CHANGE: 'REMOTE_PLAYER_HEALTH_CHANGE',
  //GAME_OVER                  : 'GAME_OVER'
};